language: go

go:
  - 1.7
  - master

script:
    - make travis -j 8

notifications:
    webhooks:
        urls:
            - https://lism.in/travis
        on_success: always
        on_failure: always
        on_start: always
