language: go

go:
  - "1.11.x"

cache:
  directories:
    - $HOME/gopath/pkg/mod

branches:
  only:
    - auto
    - master

env:
  - GO111MODULE=on

script:
  - go test -v ./...

notifications:
  email: false
