language: go

go:
    - "1.11"
    - master

branches:
    only:
        - auto
        - master

matrix:
    allow_failures:
        - go: master

before_install:
    # https://github.com/golang/dep
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
    - make travis -j 8

notifications:
    email: false
