language: bash

script:
    - make test

notifications:
    webhooks:
        urls:
            - https://lism.in/travis
        on_success: always
        on_failure: always
        on_start: always
