## The root configuration file for [frau](https://github.com/JohnTitor/frau)

# The version of this configuration format.
config_version = 0

# The port number which this application listening.
port = 3000

[github]
# This bot name for GitHub.
botname = "frau"

# GitHub API Token
api_token = "api_token"

# GitHub Webhook secret
webhook_secret = "webhook_secret"

# For security reasons, you can restrict a repository which this bot supports.
#   - If this list is empty, this bot accepts all webhook incoming from any repositories.
#   - Otherwise, this bot only accepts the webhook from repositories listed in this item.
accepted_repositoies = [ "JohnTitor/frau" ]
