
[[constraint]]
  name = "github.com/BurntSushi/toml"
  revision = "a368813c5e648fee92e5f6c30e3944ff9d5e8895"

[[constraint]]
  name = "github.com/google/go-github"
  revision = "de33c46a823d3f723514fc5333b75ef2e937b7df"
