
[[dependencies]]
  name = "github.com/BurntSushi/toml"
  revision = "b26d9c308763d68093482582cea63d69be07a0f0"

[[dependencies]]
  name = "github.com/google/go-github"
  revision = "c9c37fd6ce0247943d1aa34fc3813c62c5cb0225"
