name: Go CI
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
          id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run build
        run: go build -v

      - name: Run test
        run: go test -v -race ./...

      - name: Check formatting
        run: (! gofmt -s -d . | grep '^')

      - name: Check with `go vet`
        run: go vet ./...
